---
name: mena
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.4
  retrofit: ^4.0.1
  dio: ^5.0.3
  analyzer: ^5.10.0
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1
  build_runner: ^2.3.3
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.1.0
  freezed: ^2.3.2
  get_it: ^7.2.0
  lottie: ^2.3.2
  country_code_picker: ^3.0.0
  image_picker: ^0.8.7+3
  rxdart: ^0.27.7
  carousel_slider: ^4.2.1
  easy_localization: ^3.0.1
  flutter_phoenix: ^1.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/splash_logo.png
  - assets/images/onboarding_logo1.svg
  - assets/images/onboarding_logo2.svg
  - assets/images/onboarding_logo3.svg
  - assets/images/onboarding_logo4.svg
  - assets/images/right_arrow_ic.svg
  - assets/images/left_arrow_ic.svg
  - assets/images/settings_right_arrow_ic.svg
  - assets/images/change_lang_ic.svg
  - assets/images/contact_us_ic.svg
  - assets/images/hollow_cirlce_ic.svg
  - assets/images/solid_circle_ic.svg
  - assets/images/invite_friends_ic.svg
  - assets/images/logout_ic.svg
  - assets/images/photo_camera_ic.svg
  - assets/json/loading.json
  - assets/json/error.json
  - assets/json/empty.json
  - assets/json/success.json
  - assets/translations/ar-SA.json
  - assets/translations/en-US.json

  fonts:
  - family: Montserrat
    fonts:
    - asset: assets/fonts/Montserrat-Bold.ttf
      weight: 700
    - asset: assets/fonts/Montserrat-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Montserrat-Medium.ttf
      weight: 500
    - asset: assets/fonts/Montserrat-Regular.ttf
      weight: 400
    - asset: assets/fonts/Montserrat-Light.ttf
      weight: 300
assets/images/onboarding_logo1:
  svg: null
